import { useEffect, useRef, useState, type ReactNode, type MouseEvent } from 'react'
import { useInView } from 'motion/react'
import { experience, projects, projectDetails, skills, skillIcons, education, achievements, interests, profile } from '../data'
import FadeContent from './FadeContent'
import Character from './Character'
import { signalCompanion } from './Hero'
import Activity from './Activity'
import './Portfolio.css'

function Heading({ number, name, line }: { number: string; name: string; line: string }) { return <div className="chapter-heading"><p><span>{number}</span> {name}</p><h2>{line}</h2></div> }
function Chapter({ id, children }: { id: string; children: ReactNode }) { return <section id={id} className="chapter wrap"><FadeContent>{children}</FadeContent></section> }
export function DetailIcon({ kind }: { kind: string }) { return <svg className="detail-icon" viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="miter" aria-hidden="true">{kind === 'hat' ? <><path d="M5 30h38v6H5zM12 29l4-15h16l4 15" fill="#d3b46d" /><path d="M13 24h22v6H13" fill="#ae6665" /></> : kind === 'chess' ? <><path d="M12 40h24v-5H12zM17 34l3-9-6-3 4-12 13 5 3 9-6 9M19 10V6l8 7" fill="#b7c8c9" /><path d="M23 17h3" stroke="#151c2a" /></> : kind === 'cube' ? <><path d="M8 13l16-8 16 8v22l-16 8-16-8zM8 13l16 8 16-8M24 21v22M8 24l16 8 16-8M16 9l16 8v22M32 9l-16 8v22" fill="#759795" /></> : kind === 'ball' ? <><circle cx="24" cy="24" r="18" fill="#dbd6c6" /><path d="m24 15 9 6-4 10H18l-3-10zM24 6v9M7 19l8 2M14 39l4-8M36 38l-7-7M42 18l-9 3" fill="#263446" /></> : <><path d="M15 7h18v14l-5 7h-8l-5-7zM15 11H7v9l8 5M33 11h8v9l-8 5M24 28v9M15 41h18v-4H15z" fill="#b99b59" /><path d="m24 12 2 4 4 1-3 3 1 4-4-2-4 2 1-4-3-3 4-1z" fill="#eee0b1" strokeWidth="1" /></>}</svg> }
function About() { const [interest, setInterest] = useState<number | null>(null), [pulse, setPulse] = useState(0); function choose(i: number) { setInterest(i); setPulse(n => n + 1) } return <Chapter id="about"><div className="about-layout"><Heading number="01" name="About" line="Behind the keyboard." /><div className="about-prose"><p className="lead">Useful applications.<br /><em>Interesting problems.</em></p><p>I'm Saheem, a full-stack developer who works across React interfaces, REST APIs, and databases. My experience spans freelance projects, business applications, and backend testing.</p><p>I'm studying Computer Science and Engineering with a focus on AI and Machine Learning at Finolex Academy of Management and Technology. I enjoy building things and working through data structures and algorithms.</p></div></div><div className="beyond"><div><h3>Beyond code</h3><p>A few things I make time for.</p></div><div className="interest-items">{interests.map((item, i) => <button key={item.name} aria-pressed={interest === i} data-interest={item.icon} onPointerEnter={e => { if (e.pointerType === 'mouse') choose(i) }} onFocus={() => choose(i)} onClick={() => choose(i)}><span className="interest-stage" key={`${i}-${interest === i ? pulse : 0}`}><DetailIcon kind={item.icon} /></span><span>{item.name}</span></button>)}</div><p className="interest-note" aria-live="polite">{interest === null ? 'Pick an interest to explore.' : interests[interest].note}</p></div></Chapter> }
function Experience() { const [selected, setSelected] = useState<number | null>(0); return <Chapter id="experience"><Heading number="02" name="Experience" line="A few chapters of building." /><div className="career-timeline">{experience.map((job, i) => <article className={`career-entry ${selected === i ? 'selected' : ''}`} key={job.company}><div className="career-date"><span className="timeline-dot" />{job.date}<small>{job.location}</small></div><div className="career-body"><p className="career-company">{job.company}</p><h3>{job.role}</h3><button className="responsibility-toggle" aria-expanded={selected === i} aria-controls={`role-${i}`} onClick={() => setSelected(selected === i ? null : i)}>{selected === i ? 'Hide responsibilities' : 'View responsibilities'} <span aria-hidden="true">{selected === i ? '−' : '+'}</span></button><div id={`role-${i}`} hidden={selected !== i}><ul>{job.points.map(point => <li key={point}>{point}</li>)}</ul></div></div></article>)}</div></Chapter> }
function Projects() {
    const [active, setActive] = useState<number | null>(null), [flash, setFlash] = useState<number | null>(null)
    const dialog = useRef<HTMLDialogElement>(null), trigger = useRef<HTMLElement | null>(null), flashTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
    useEffect(() => () => clearTimeout(flashTimer.current), [])
    function open(i: number, event: MouseEvent<HTMLButtonElement>) { trigger.current = event.currentTarget; signalCompanion(i === 0 ? 'project-instagram' : 'project-urban'); setActive(i); dialog.current?.showModal(); document.body.style.overflow = 'hidden' }
    function close() { dialog.current?.close(); document.body.style.overflow = ''; trigger.current?.focus() }
    function preview(i: number) { setFlash(i); clearTimeout(flashTimer.current); flashTimer.current = setTimeout(() => setFlash(null), 260) }
    return <Chapter id="projects"><Heading number="03" name="Projects" line="Ideas, made tangible." /><div className="showcases">{projects.map((p, i) => <article className={`showcase showcase-${i}`} key={p.name}><div className={`showcase-preview ${flash === i ? 'pixel-flash' : ''}`} onPointerEnter={() => preview(i)}><div className="preview-top"><span>0{i + 1}</span><span>{i === 0 ? 'Social application' : 'Civic technology'}</span></div>{projectDetails[i].screenshot ? <img src={projectDetails[i].screenshot} width="1200" height="800" loading="lazy" alt="Actual Urban Tracker sign-in page" /> : <div className="social-illustration" aria-label="Concept illustration of social connections"><svg viewBox="0 0 320 180" aria-hidden="true"><path d="M80 45h160v90H80zM80 60 30 100l50 20M240 60l50 40-50 20" fill="none" stroke="#628887" strokeWidth="2" strokeDasharray="5 6" /><rect x="115" y="46" width="90" height="88" fill="#182735" stroke="#b4cfae" strokeWidth="3" /><circle cx="160" cy="80" r="13" fill="#c4b2d9" /><path d="M138 112q22-26 44 0" fill="#c4b2d9" /><rect x="17" y="87" width="26" height="26" fill="#cbb485" /><rect x="277" y="87" width="26" height="26" fill="#9db9b4" /></svg><span>Connection, in real time.</span></div>}<button className="preview-open" aria-label={`Explore ${p.name}`} onClick={e => { preview(i); open(i, e) }}>View project <span aria-hidden="true">↗</span></button><p className="preview-caption">{projectDetails[i].visualCaption}</p><div className="pixel-wipe" aria-hidden="true">{Array.from({ length: 24 }, (_, n) => <i key={n} style={{ animationDelay: `${(n * 7) % 70}ms` }} />)}</div></div><div className="showcase-copy"><p className="small-label">{p.category.toLowerCase()}</p><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tech.map(t => <span key={t}>{t}</span>)}</div><p className="contribution-label">My contribution</p><p>{projectDetails[i].contribution}</p><div className="project-actions"><button className="small-button" onFocus={() => preview(i)} onClick={e => { preview(i); open(i, e) }}>Explore project</button><a className="text-link" href={p.repo} target="_blank" rel="noreferrer">Repository</a>{projectDetails[i].demo && <a className="text-link" href={projectDetails[i].demo!} target="_blank" rel="noreferrer">Live demo</a>}</div></div></article>)}</div>
        <dialog ref={dialog} className="project-dialog" aria-labelledby="project-title" onCancel={e => { e.preventDefault(); close() }} onClose={() => { document.body.style.overflow = ''; trigger.current?.focus() }} onKeyDown={e => { if (e.key !== 'Tab') return; const nodes = dialog.current?.querySelectorAll<HTMLElement>('button,a[href]'); if (!nodes?.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus() } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus() } }}><div className="dialog-bar"><span>Project notes</span><button onClick={close} aria-label="Close project details" autoFocus>Close ×</button></div>{active !== null && <div className="project-dialog-content"><h2 id="project-title">{projects[active].name}</h2><p>{projects[active].description}</p><h3>Technical features</h3><ul>{projects[active].features.map(f => <li key={f}>{f}</li>)}</ul><h3>My contribution</h3><p>{projectDetails[active].contribution}</p><h3>Technology stack</h3><div className="tags">{projects[active].tech.map(t => <span key={t}>{t}</span>)}</div><a className="small-button" href={projects[active].repo} target="_blank" rel="noreferrer">Open repository</a>{projectDetails[active].demo && <a className="text-link" href={projectDetails[active].demo!} target="_blank" rel="noreferrer">Open demo</a>}</div>}</dialog></Chapter>
}
function Skills() { const [category, setCategory] = useState('All'); const list = Object.entries(skills).filter(([group]) => category === 'All' || category === group); return <Chapter id="skills"><Heading number="04" name="Skills" line="Tools in my inventory." /><div className="inventory"><div className="skill-filters" role="group" aria-label="Filter skills by category">{['All', ...Object.keys(skills)].map(group => <button key={group} aria-pressed={category === group} onClick={() => setCategory(group)}>{group}</button>)}</div><p className="inventory-status" role="status">{category === 'All' ? 'All categories' : category} · {list.reduce((n, [, items]) => n + items.length, 0)} skills</p><div className="inventory-items">{list.flatMap(([group, items]) => items.map(name => <div className="inventory-item" key={name}>{skillIcons[name] ? <img src={`/icons/${skillIcons[name]}.svg`} alt="" width="25" height="25" loading="lazy" /> : <span className="generic-tech" aria-hidden="true">{name === 'VS Code' ? '〈〉' : name === 'SQL' ? 'DB' : name === 'REST APIs' ? 'API' : '⌘'}</span>}<div><span>{name}</span><small>{group}</small></div></div>))}</div></div><p className="foundations">Foundations: Data Structures & Algorithms · OOP · DBMS · Operating Systems · Computer Networks</p></Chapter> }
function Achievements() { const ref = useRef<HTMLDivElement>(null), seen = useInView(ref, { once: true, amount: .25 }), announced = useRef(false); useEffect(() => { if (seen && !announced.current) { announced.current = true; signalCompanion('smiling') } }, [seen]); return <Chapter id="achievements"><div ref={ref}><Heading number="05" name="Achievements" line="A few things I’m proud of." /><div className="trophy-shelf">{achievements.map((name, i) => <article key={name}><div className={`trophy-badge badge-${i}`}><DetailIcon kind="trophy" /><span>{['01', '02', '03', 'DSA', 'AI'][i]}</span></div><h3>{name}</h3></article>)}</div></div><div className="education-strip"><h3>Education</h3>{education.map(item => <article key={item.school}><p className="small-label">{item.date}</p><h4>{item.school}</h4><p>{item.degree}</p><strong>{item.result}</strong></article>)}</div></Chapter> }
function Contact() { const [copied, setCopied] = useState(''), ref = useRef<HTMLDivElement>(null), seen = useInView(ref, { once: true, amount: .3 }), sent = useRef(false); useEffect(() => { if (seen && !sent.current) { sent.current = true; signalCompanion('farewell') } }, [seen]); async function copy() { try { await navigator.clipboard.writeText(profile.email); setCopied('Email copied. Ready when you are.') } catch { setCopied('Copy unavailable. Select the email address below to copy it.') } } return <Chapter id="contact"><div className="closing" ref={ref}><div><p className="small-label">07 / Contact</p><h2>Let’s build<br />the next thing.</h2><p>Have an application in mind, a team to join,<br className="desktop-br" /> or a problem worth solving? Let's talk.</p><a className="closing-email" href={`mailto:${profile.email}`}>{profile.email}</a><div className="closing-actions"><button className="small-button" onClick={copy}>Copy email</button><a className="text-link" href="/Saheem_Nakhwa_Resume.pdf" target="_blank" rel="noreferrer">View resume</a><a className="text-link" href="/Saheem_Nakhwa_Resume.pdf" download>Download PDF</a></div><p className="copy-status" role="status">{copied}</p><div className="closing-socials">{profile.links.map(link => <a key={link.name} href={link.url} target="_blank" rel="noreferrer">{link.name}</a>)}</div></div><div className="farewell-character"><span>See you on the next quest.</span><Character state="smiling" animate={false} /><div className="character-platform" /></div></div></Chapter> }
export default function Portfolio() { return <div className="portfolio-world"><About /><Experience /><Projects /><Skills /><Achievements /><Chapter id="activity"><Heading number="06" name="Coding activity" line="Small steps, committed." /><Activity /></Chapter><Contact /></div> }

