export const profile={name:'Saheem Nakhwa',email:'saheem.nakhwa24@gmail.com',links:[{name:'GitHub',url:'https://github.com/saheemOlogN'},{name:'LinkedIn',url:'https://www.linkedin.com/in/saheemnakhwa/'},{name:'LeetCode',url:'https://leetcode.com/u/xiaowarma/'}]} as const
 type Experience={role:string;company:string;date:string;location:string;points:string[]}
export const experience:Experience[]=[
{role:'Backend System Coordinator',company:'Royal Consultants',date:'Sep 2025 - Mar 2026',location:'Remote',points:['Conducted functional and API testing for ERP modules to validate business workflows.','Diagnosed and resolved REST API issues, and worked with developers to reproduce, document, and verify bug fixes.']},
{role:'Full Stack Developer Intern',company:'Emirates Solutions',date:'Apr 2024 - Jun 2024',location:'Ratnagiri',points:['Assisted in modernizing WordPress-based solutions toward a MERN architecture.','Developed PHP business application modules integrated with MySQL, implemented features, and resolved defects.']},
{role:'Freelance Full Stack Developer',company:'Independent',date:'2023 - Present',location:'Remote',points:['Delivered 5+ web development projects for clients across different domains.','Built applications with React.js, Node.js, Express.js, MongoDB, and MySQL, owning requirements, deployment, and maintenance.']}]
 type Project={name:string;category:string;description:string;features:string[];tech:string[];repo:string}
export const projects:Project[]=[{name:'Instagram Clone',category:'FULL STACK / SOCIAL',description:'A social application built around real-time conversations and media sharing.',features:['Implemented Socket.IO messaging and notifications.','Integrated Cloudinary media delivery, JWT authentication, protected routes, and Redux Toolkit state management.'],tech:['React','Express','MongoDB','Redux','Socket.IO','Cloudinary','ShadCN UI'],repo:'https://github.com/saheemOlogN/Instagram-Clone'},{name:'Urban Tracker',category:'FULL STACK / CIVIC TECH',description:'A citizen-focused platform for reporting civic issues and finding public services in Ratnagiri.',features:['Built digital complaint submission and tracking.','Centralized hospitals, schools, and government facility information as a hackathon governance solution.'],tech:['React','Node.js','Express','MongoDB'],repo:'https://github.com/saheemOlogN/Urban-Tracker'}]
export const skills:Record<string,string[]>={'Frontend':['React.js','Tailwind CSS','Bootstrap','ShadCN UI','EJS','HTML/CSS'],'Backend':['Node.js','Express.js','PHP','REST APIs'],'Databases':['MongoDB','MySQL'],'Languages':['JavaScript','C','C++','Java','Python','SQL'],'AI / ML & Data':['PyTorch','Hugging Face','Fine-Tuning','NLP','Computer Vision','Model Training','NumPy','Pandas','Matplotlib'],'Tools':['Git','GitHub','Postman','Linux','VS Code']}
export const education=[{school:'Finolex Academy of Management and Technology',date:'2025 - Present',degree:'B.E. Computer Science and Engineering (Artificial Intelligence & Machine Learning)',result:'CGPA: 8.7'},{school:'Government Polytechnic Ratnagiri',date:'2023 - 2025',degree:'Diploma in Computer Engineering',result:'Aggregate: 87.94%'}] as const
export const achievements=['1st Rank in State-Level Diploma Project Competition','Winner of State-Level Web Development Competition (2 Times)','Winner of Inter-College Competitive Programming Competition','Solved 150+ DSA Problems','AI & Machine Learning Course - CodeWithHarry'] as const

export const projectDetails = [
 {contribution:'Implemented real-time messaging and notifications, media handling, authentication, protected routes, and centralized application state.', screenshot:null, demo:null, visualCaption:'Concept illustration, not an application screenshot.'},
 {contribution:'Built the citizen reporting and complaint-tracking experience, and centralized information about public facilities for a Ratnagiri hackathon governance solution.', screenshot:'/art/projects/urban-tracker-login.png', demo:'https://urban-tracker-vcdu.vercel.app', visualCaption:'Actual Urban Tracker sign-in screen. The application requires an account.'}
] as const
export const interests = [
 {name:'One Piece',icon:'hat',note:'Always room for another adventure.'},
 {name:'Chess',icon:'chess',note:'One move at a time.'},
 {name:'Rubik’s cube',icon:'cube',note:'A different kind of problem-solving.'},
 {name:'Football',icon:'ball',note:'Time away from the keyboard.'}
] as const
export const skillIcons:Record<string,string>={'React.js':'react','Tailwind CSS':'tailwindcss','Bootstrap':'bootstrap','ShadCN UI':'shadcnui','EJS':'ejs','HTML/CSS':'html5','Node.js':'nodedotjs','Express.js':'express','PHP':'php','MongoDB':'mongodb','MySQL':'mysql','JavaScript':'javascript','C':'c','C++':'cplusplus','Java':'openjdk','Python':'python','PyTorch':'pytorch','Hugging Face':'huggingface','NumPy':'numpy','Pandas':'pandas','Git':'git','GitHub':'github','Postman':'postman','Linux':'linux'}
